# Generated by Django 5.2.8 on 2025-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order_orderitem_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
