# Generated by Django 5.2.8 on 2025-11-23 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_paid_order_is_paid_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название скидки (например, 'Летняя распродажа')", max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Процентная'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Значение скидки: процент (например, 10 для 10%) или сумма в центах')),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='ID купона в Stripe (опционально)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название налога (например, 'НДС', 'Sales Tax')", max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Процент налога (например, 20.00 для 20%)', max_digits=5)),
                ('stripe_tax_rate_id', models.CharField(blank=True, help_text='ID налоговой ставки в Stripe (опционально)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='items.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='items.tax'),
        ),
    ]
