# Generated by Django 5.0 on 2025-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax',
            name='stripe_tax_rate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
